export const PackagingFacetAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'allowance',
    inputs: [
      { name: 'tokenId_', type: 'uint256', internalType: 'uint256' },
      { name: 'operator_', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'to_', type: 'address', internalType: 'address' },
      { name: 'tokenId_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'tokenId_', type: 'uint256', internalType: 'uint256' },
      { name: 'to_', type: 'address', internalType: 'address' },
      { name: 'value_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner_', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'balance', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'tokenId_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancel',
    inputs: [{ name: 'slot_', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'contractURI',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: 'tokenId_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSlotInfo',
    inputs: [{ name: 'slot_', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct BundlingSlotInfo',
        components: [
          {
            name: 'bundledTokenId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'bundledAsset',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'originator',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'bundledSlotBoundAcct',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'tokenIds',
            type: 'uint256[]',
            internalType: 'uint256[]',
          },
          {
            name: 'totalAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [{ name: 'decimals_', type: 'uint8', internalType: 'uint8' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: 'owner_', type: 'address', internalType: 'address' },
      { name: 'operator_', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'metadataDescriptor',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IERC3525MetadataDescriptorUpgradeable',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'tokenId_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'owner_', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pack',
    inputs: [
      {
        name: 'input_',
        type: 'tuple',
        internalType: 'struct BunlingInput',
        components: [
          { name: 'name', type: 'string', internalType: 'string' },
          {
            name: 'bundledAsset',
            type: 'address',
            internalType: 'address',
          },
          { name: 'salt', type: 'bytes32', internalType: 'bytes32' },
          {
            name: 'tokenIds',
            type: 'uint256[]',
            internalType: 'uint256[]',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from_', type: 'address', internalType: 'address' },
      { name: 'to_', type: 'address', internalType: 'address' },
      { name: 'tokenId_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from_', type: 'address', internalType: 'address' },
      { name: 'to_', type: 'address', internalType: 'address' },
      { name: 'tokenId_', type: 'uint256', internalType: 'uint256' },
      { name: 'data_', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'operator_', type: 'address', internalType: 'address' },
      { name: 'approved_', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'slotByIndex',
    inputs: [{ name: 'index_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'slotCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'slotOf',
    inputs: [{ name: 'tokenId_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'slotURI',
    inputs: [{ name: 'slot_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenByIndex',
    inputs: [{ name: 'index_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenInSlotByIndex',
    inputs: [
      { name: 'slot_', type: 'uint256', internalType: 'uint256' },
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenOfOwnerByIndex',
    inputs: [
      { name: 'owner_', type: 'address', internalType: 'address' },
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenSupplyInSlot',
    inputs: [{ name: 'slot_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      {
        name: 'fromTokenId_',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'to_', type: 'address', internalType: 'address' },
      { name: 'value_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'newTokenId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from_', type: 'address', internalType: 'address' },
      { name: 'to_', type: 'address', internalType: 'address' },
      { name: 'tokenId_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      {
        name: 'fromTokenId_',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'toTokenId_', type: 'uint256', internalType: 'uint256' },
      { name: 'value_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'valueDecimals',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      {
        name: '_owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_approved',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_tokenId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ApprovalForAll',
    inputs: [
      {
        name: '_owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_operator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_approved',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ApprovalValue',
    inputs: [
      {
        name: '_tokenId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: '_operator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_value',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint8',
        indexed: false,
        internalType: 'uint8',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Packed',
    inputs: [
      {
        name: 'operator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'name',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'sba',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'slot',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'tokenId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetMetadataDescriptor',
    inputs: [
      {
        name: 'metadataDescriptor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SlotChanged',
    inputs: [
      {
        name: '_tokenId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: '_oldSlot',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: '_newSlot',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      {
        name: '_from',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: '_tokenId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TransferValue',
    inputs: [
      {
        name: '_fromTokenId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: '_toTokenId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: '_value',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'BundlingAlreadyExists', inputs: [] },
  { type: 'error', name: 'InsufficientFunds', inputs: [] },
  {
    type: 'error',
    name: 'NotAllowedAsset',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
  },
  { type: 'error', name: 'NotAuthorized', inputs: [] },
] as const;

export const hyperPoolingAbi = [
  {
    type: 'function',
    name: 'getPooledAssetsValue',
    inputs: [{ name: 'fpAddr_', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
